### PR TITLE
build binaries for Linux ARM64

### PR DESCRIPTION
**Pull request by tsnobip**
Today rescript ships bsb for ARM64 but not rewatch, so this PR allows rewatch to support the same targets.

### CODE REVIEW

**Review by rolandpeelen — APPROVED** [review]
Nice!

**Comment by rolandpeelen** [comment]
@tsnobip - I’ll have a look tomorrow. Seems that the musl build should, just work (tm). But I’ll have a look. 

What exact OS are you on? And are you deploying inside a docker? What can I do to reproduce / have a look?

**Comment by tsnobip** [comment]
> @tsnobip - I’ll have a look tomorrow. Seems that the musl build should, just work (tm). But I’ll have a look.
> 
> What exact OS are you on? And are you deploying inside a docker? What can I do to reproduce / have a look?

@rolandpeelen  yes the build is inside docker, it uses node:22.1.0-alpine3.19 docker image as base but I don't have a repro open-sourced.

**Comment by tsnobip** [comment]
I think I found the issue

**Comment by tsnobip** [comment]
it's all working now!

**Comment by rolandpeelen** [comment]
@tsnobip -- Nice! Yeah, that might be the one. Awesome. I tried locally, seems to work for me too 🙌. Feel free to merge!

**Pull request merged**
